# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-09 18:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adeia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adeiatype', models.CharField(blank=True, choices=[('1', '\u039a\u03b1\u03bd\u03bf\u03bd\u03b9\u03ba\u03ae'), ('2', '\u0391\u03bd\u03b1\u03c1\u03c1\u03c9\u03c4\u03b9\u03ba\u03ae'), ('3', '\u0395\u03bf\u03c1\u03c4\u03b1\u03c3\u03c4\u03b9\u03ba\u03ae')], default='-', max_length=50, verbose_name='\u03a4\u03cd\u03c0\u03bf\u03c2 \u0386\u03b4\u03b5\u03b9\u03b1\u03c2')),
                ('startdate', models.CharField(max_length=100, verbose_name='\u0391\u03c0\u03cc')),
                ('enddate', models.CharField(max_length=100, verbose_name='\u0388\u03c9\u03c2')),
                ('createddate', models.CharField(max_length=100, verbose_name='\u0397\u03bc. \u0394\u03b7\u03bc\u03bf\u03c5\u03c1\u03b3\u03af\u03b1\u03c2')),
                ('employee', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u03a5\u03c0\u03ac\u03bb\u03bb\u03b7\u03bb\u03bf\u03c2')),
            ],
            options={
                'verbose_name': '\u0386\u03b4\u03b5\u03b9\u03b5\u03c2',
                'verbose_name_plural': '\u0386\u03b4\u03b5\u03b9\u03b5\u03c2',
            },
        ),
        migrations.CreateModel(
            name='Aithmata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importdate', models.CharField(max_length=100, verbose_name='\u0397\u03bc. \u039a\u03b1\u03c4\u03b1\u03c7\u03ce\u03c1\u03b7\u03c3\u03b7\u03c2')),
                ('info', models.TextField(max_length=500, verbose_name='\u03a0\u03b5\u03c1\u03b9\u03b3\u03c1\u03b1\u03c6\u03ae')),
                ('employee', models.CharField(max_length=100, verbose_name='\u038c\u03bd. \u03a5\u03c0\u03b1\u03bb\u03bb\u03ae\u03bb\u03bf\u03c5')),
                ('closedate', models.CharField(max_length=100, verbose_name='\u0397\u03bc. \u039a\u03bb\u03b5\u03b9\u03c3\u03af\u03bc\u03b1\u03c4\u03bf\u03c2')),
                ('assign', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u03a7\u03c1\u03ad\u03c9\u03c3\u03b7')),
            ],
            options={
                'verbose_name': '\u0391\u03b9\u03c4\u03ae\u03bc\u03b1\u03c4\u03b1',
                'verbose_name_plural': '\u0391\u03b9\u03c4\u03ae\u03bc\u03b1\u03c4\u03b1',
            },
        ),
        migrations.CreateModel(
            name='Dhmos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u03a0\u03b5\u03bb\u03ac\u03c4\u03b7\u03c2')),
                ('phone', models.CharField(max_length=100, verbose_name='\u03a4\u03b7\u03bb\u03ad\u03c6\u03c9\u03bd\u03bf')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='Fax')),
                ('teamviewer', models.CharField(blank=True, max_length=60, verbose_name='TeamViewer')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True, max_length=250, null=True)),
                ('info', models.TextField(blank=True, max_length=1000, verbose_name='\u03a0\u03bb\u03b7\u03c1\u03bf\u03c6\u03bf\u03c1\u03af\u03b5\u03c2')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u03a0\u03b5\u03bb\u03ac\u03c4\u03b5\u03c2',
                'verbose_name_plural': '\u03a0\u03b5\u03bb\u03ac\u03c4\u03b5\u03c2',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=150, null=True, verbose_name='\u038c\u03bd\u03bf\u03bc\u03b1')),
                ('lastname', models.CharField(max_length=150, null=True, verbose_name='\u0395\u03c0\u03ce\u03bd\u03c5\u03bc\u03bf')),
                ('tmhma', models.CharField(blank=True, choices=[('1', '\u039f\u03b9\u03ba\u03bf\u03bd\u03bf\u03bc\u03b9\u03ba\u03ae'), ('2', '\u03a4\u03b5\u03c7\u03bd\u03b9\u03ba\u03ae'), ('3', '\u0394\u03b9\u03bf\u03b9\u03ba\u03b7\u03c4\u03b9\u03ba\u03ae'), ('4', '\u0393\u03c1\u03b1\u03c6\u03b5\u03af\u03bf \u03a0\u03c1\u03bf\u03c3\u03c9\u03c0\u03b9\u03ba\u03bf\u03cd'), ('5', '\u039c\u03b9\u03c3\u03b8\u03bf\u03b4\u03bf\u03c3\u03af\u03b1'), ('6', '\u0393\u03c1\u03b1\u03c6\u03b5\u03af\u03bf \u0394\u03b7\u03bc\u03ac\u03c1\u03c7\u03bf\u03c5'), ('7', '\u03a4\u03bc\u03ae\u03bc\u03b1 \u03a0\u03bb\u03b7\u03c1\u03bf\u03c6\u03bf\u03c1\u03b9\u03ba\u03ae\u03c2'), ('8', '\u039b\u03b7\u03be\u03b9\u03b1\u03c1\u03c7\u03b5\u03af\u03bf')], max_length=100, verbose_name='\u03a5\u03c0\u03b7\u03c1\u03b5\u03c3\u03af\u03b1')),
                ('phone', models.CharField(max_length=100, verbose_name='\u03a4\u03b7\u03bb\u03ad\u03c6\u03c9\u03bd\u03bf')),
                ('cellphone', models.CharField(blank=True, max_length=30, verbose_name='\u039a\u03b9\u03bd\u03b7\u03c4\u03cc')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('info', models.TextField(blank=True, max_length=1000, verbose_name='\u03a0\u03bb\u03b7\u03c1\u03bf\u03c6\u03bf\u03c1\u03af\u03b5\u03c2')),
                ('dhmos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dhmoi.Dhmos', verbose_name='\u0394\u03ae\u03bc\u03bf\u03c2')),
            ],
            options={
                'verbose_name': '\u03a3\u03c4\u03bf\u03b9\u03c7\u03b5\u03af\u03b1 \u0395\u03c0\u03b9\u03ba\u03bf\u03b9\u03bd\u03c9\u03bd\u03af\u03b1\u03c2 \u03a0\u03b5\u03bb\u03b1\u03c4\u03ce\u03bd',
                'verbose_name_plural': '\u03a3\u03c4\u03bf\u03b9\u03c7\u03b5\u03af\u03b1 \u0395\u03c0\u03b9\u03ba\u03bf\u03b9\u03bd\u03c9\u03bd\u03af\u03b1\u03c2 \u03a0\u03b5\u03bb\u03b1\u03c4\u03ce\u03bd',
            },
        ),
        migrations.CreateModel(
            name='Ergasies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importdate', models.DateField(verbose_name='\u0397\u03bc. \u039a\u03b1\u03c4.')),
                ('app', models.CharField(blank=True, choices=[('\u03a4\u0391\u03a0', '\u03a4\u0391\u03a0'), ('\u039c\u03b9\u03c3\u03b8\u03bf\u03b4\u03bf\u03c3\u03af\u03b1', '\u039c\u03b9\u03c3\u03b8\u03bf\u03b4\u03bf\u03c3\u03af\u03b1'), ('\u0394\u03b9\u03b1\u03c7\u03b5\u03af\u03c1\u03b9\u03c3\u03b7 \u03a0\u03c1\u03bf\u03c3\u03c9\u03c0\u03b9\u03ba\u03bf\u03cd', '\u0394\u03b9\u03b1\u03c7\u03b5\u03af\u03c1\u03b9\u03c3\u03b7 \u03a0\u03c1\u03bf\u03c3\u03c9\u03c0\u03b9\u03ba\u03bf\u03cd'), ('\u039b\u03bf\u03b3\u03b9\u03c3\u03c4\u03b9\u03ba\u03ae', '\u039b\u03bf\u03b3\u03b9\u03c3\u03c4\u03b9\u03ba\u03ae'), ('\u039c\u03b7\u03c4\u03c1\u03ce\u03bf \u03a0\u03bf\u03bb\u03b9\u03c4\u03ce\u03bd', '\u039c\u03b7\u03c4\u03c1\u03ce\u03bf \u03a0\u03bf\u03bb\u03b9\u03c4\u03ce\u03bd'), ('\u038e\u03b4\u03c1\u03b5\u03c5\u03c3\u03b7', '\u038e\u03b4\u03c1\u03b5\u03c5\u03c3\u03b7'), ('\u03a0\u03c1\u03c9\u03c4\u03cc\u03ba\u03bf\u03bb\u03bb\u03bf', '\u03a0\u03c1\u03c9\u03c4\u03cc\u03ba\u03bf\u03bb\u03bb\u03bf'), ('\u0394\u03b9\u03b1\u03cd\u03b3\u03b5\u03b9\u03b1', '\u0394\u03b9\u03b1\u03cd\u03b3\u03b5\u03b9\u03b1'), ('\u0388\u03c3\u03bf\u03b4\u03b1', '\u0388\u03c3\u03bf\u03b4\u03b1'), ('\u039a\u03bf\u03b9\u03bc\u03b7\u03c4\u03ae\u03c1\u03b9\u03b1', '\u039a\u03bf\u03b9\u03bc\u03b7\u03c4\u03ae\u03c1\u03b9\u03b1'), ('\u039a\u039f\u039a', '\u039a\u039f\u039a'), ('\u0394\u03b7\u03bc\u03bf\u03c4\u03b9\u03ba\u03cc\u03c2 \u03c6\u03cc\u03c1\u03bf\u03c2', '\u0394\u03b7\u03bc\u03bf\u03c4\u03b9\u03ba\u03cc\u03c2 \u03c6\u03cc\u03c1\u03bf\u03c2'), ('Site', 'Site'), ('\u03a0\u03c1\u03b1\u03ba\u03c4\u03b9\u03ba\u03cc', '\u03a0\u03c1\u03b1\u03ba\u03c4\u03b9\u03ba\u03cc')], max_length=100, verbose_name='\u0395\u03c6\u03b1\u03c1\u03bc\u03bf\u03b3\u03ae')),
                ('jobtype', models.CharField(choices=[('TeamViewer', 'TeamViewer'), ('\u0395\u03c0\u03af\u03c3\u03ba\u03b5\u03c8\u03b7', '\u0395\u03c0\u03af\u03c3\u03ba\u03b5\u03c8\u03b7'), ('\u0393\u03c1\u03b1\u03c6\u03b5\u03af\u03bf', '\u0393\u03c1\u03b1\u03c6\u03b5\u03af\u03bf')], default='TeamViewer', max_length=100, verbose_name='\u03a4\u03cd\u03c0\u03bf\u03c2 \u0395\u03c1\u03b3\u03b1\u03c3\u03af\u03b1\u03c2')),
                ('info', models.TextField(max_length=1000, verbose_name='\u03a0\u03b5\u03c1\u03b9\u03b3\u03c1\u03b1\u03c6\u03ae')),
                ('text', models.TextField(blank=True, max_length=1000, verbose_name='\u03a3\u03b7\u03bc\u03b5\u03b9\u03ce\u03c3\u03b5\u03b9\u03c2')),
                ('time', models.CharField(default=0, max_length=20, verbose_name='\u0394\u03b9\u03ac\u03c1\u03ba\u03b5\u03b9\u03b1')),
                ('name', models.CharField(blank=True, help_text='\u0395\u03c0\u03ce\u03bd\u03c5\u03bc\u03bf-\u038c\u03bd\u03bf\u03bc\u03b1', max_length=100, null=True, verbose_name='\u03a5\u03c0\u03ac\u03bb\u03bb\u03b7\u03bb\u03bf\u03c2 \u0395\u03c0\u03b9\u03ba\u03bf\u03b9\u03bd.')),
                ('ticketid', models.CharField(blank=True, max_length=50, verbose_name='\u0391\u03af\u03c4\u03b7\u03bc\u03b1 OTS')),
                ('dhmos', models.ForeignKey(default='-', on_delete=django.db.models.deletion.CASCADE, to='dhmoi.Dhmos', verbose_name='\u03a0\u03b5\u03bb\u03ac\u03c4\u03b7\u03c2')),
                ('employee', models.ForeignKey(default='-', max_length=100, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u03a5\u03c0\u03ac\u03bb\u03bb\u03b7\u03bb\u03bf\u03c2')),
            ],
            options={
                'ordering': ['importdate'],
                'verbose_name': '\u0395\u03c1\u03b3\u03b1\u03c3\u03af\u03b5\u03c2',
                'verbose_name_plural': '\u0395\u03c1\u03b3\u03b1\u03c3\u03af\u03b5\u03c2',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customername', models.CharField(blank=True, max_length=150, verbose_name='\u039f\u03bd\u03bf\u03bc\u03b1 \u03a0\u03b5\u03bb\u03ac\u03c4\u03b7')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u03a4\u03b7\u03bb\u03ad\u03c6\u03c9\u03bd\u03bf \u03a3\u03c4\u03b1\u03b8\u03b5\u03c1\u03cc')),
                ('cellphone', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u039a\u03b9\u03bd\u03b7\u03c4\u03cc \u03a4\u03b7\u03bb\u03ad\u03c6\u03c9\u03bd\u03bf')),
                ('modelinfo', models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('desktop', 'Desktop'), ('tameiakh', '\u03a4\u03b1\u03bc\u03b5\u03b9\u03b1\u03ba\u03ae \u039c\u03b7\u03c7\u03b1\u03bd\u03ae')], max_length=150, null=True, verbose_name='\u03a4\u03cd\u03c0\u03bf\u03c2')),
                ('serialnumber', models.CharField(blank=True, max_length=100, null=True, verbose_name='S/N')),
                ('modeltype', models.CharField(blank=True, max_length=150, null=True, verbose_name='\u039c\u03bf\u03bd\u03c4\u03ad\u03bb\u03bf')),
                ('importdate', models.CharField(blank=True, max_length=150, verbose_name='\u0397\u03bc. \u0395\u03b9\u03c3\u03b1\u03b3\u03c9\u03b3\u03ae\u03c2')),
                ('info', models.TextField(blank=True, max_length=500, null=True, verbose_name='\u0394\u03b9\u03ac\u03b3\u03bd\u03c9\u03c3\u03b7')),
                ('exportdate', models.CharField(blank=True, max_length=150, verbose_name='\u0397\u03bc. \u03a0\u03b1\u03c1\u03ac\u03b4\u03bf\u03c3\u03b7\u03c2')),
                ('cost', models.IntegerField(blank=True, verbose_name='\u039a\u03cc\u03c3\u03c4\u03bf\u03c2 \u03b5\u03c0\u03b9\u03c3\u03ba\u03b5\u03c5\u03ae\u03c2')),
                ('year', models.CharField(blank=True, max_length=50, verbose_name='\u0388\u03c4\u03bf\u03c2')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u03a7\u03c1\u03ae\u03c3\u03c4\u03b7\u03c2')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Service',
            },
        ),
        migrations.AddField(
            model_name='aithmata',
            name='dhmos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dhmoi.Dhmos', verbose_name='\u0394\u03ae\u03bc\u03bf\u03c2'),
        ),
    ]
